### PR TITLE
Link parsing breaks when <atom:link> is present before <link> in a feed

### PR DESCRIPTION
**Pull request by optikfluffel**
I stumbled upon a feed having an `<atom:link />` before the `<link />` tag. I'd love to help fix this but am new to Erlang (coming from Elixir) so help would be much appreciated.

//edit: I also added an example to the test data so we have a failing test to start with 😁

### CODE REVIEW

**Comment by michaelnisi** [comment]
It might be reasonable to add a `url` property to the `feed` record for this, differentiating feed URL from link URL—keeping both. What do you think?

**Comment by michaelnisi** [comment]
Something like this 7c76ad414792bfe42a586d89fbd73e6cfbca4a26.

**Comment by optikfluffel** [comment]
Thanks, the renaming to `{Wanted, QualifiedNames}` in `feeder.erl` really helped me understand what's going on there :D

**Comment by michaelnisi** [comment]
Now, after you’ve documented the accessor function `feeder_feeds:get/2`, you just have to update it accordingly—[records](http://learnyousomeerlang.com/a-short-visit-to-common-data-structures) should be private. 

> You will often see open source software using the method shown here of having a project-wide .hrl file for records that are shared across all modules. While I felt obligated to document this use, I strongly recommend that you keep all record definitions local, within one module. If you want some other module to look at a record's innards, write functions to access its fields and keep its details as private as possible. This helps prevent name clashes, avoids problems when upgrading code, and just generally improves the readability and maintainability of your code.

And please move the travis changes into separate PR to stay in focus.

**Comment by michaelnisi** [comment]
Thank you 💯 💫

**Pull request closed without merging**
